# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    # parameters:
    #   to:
    #     type: string
    #     default: "Hello World"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 
          command: |        
            mkdir ~/test
            echo "text to output here" > ~/test/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - test/output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/test/output.txt        
  print_pipeline_id2:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  cause_error:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
  print_error:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 
          command: echo "error message because of return 1"
          when: on_fail
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - save_hello_world_output
      - print_pipeline_id2
      - print_output_file:
          requires:
            - save_hello_world_output
      - cause_error
      - print_error
